### ISSUE TITLE
The app doesn't load 

### ISSUE THREAD

**Issue by samiahmed321** [DhrumilShah98/Handyman#5]
Hi the app is not loading on android version 8.0. Can you please help me out on
![Screenshot_20200924-034435](https://user-images.githubusercontent.com/43008414/94080767-4d6ed200-fe18-11ea-90bf-48a1ab5980a1.jpg)
 this

**Comment by DhrumilShah98** [comment]
Hey
Are you able to run the website alone? (handyman-web)
Also, can you share what steps you are following?

The process is simple.
You can use tools like ngrok (https://ngrok.com/). Just type one command for, secure URL to your localhost server through any NAT or firewall. Just use the command [ngrok http 3000] and then use the URL which is generated and replace the "YOUR_HANDYMAN_URL" in MainActivity.java
